---
test-name: CommandInvokerResponseIndicatesInternalLogicError_ThrowsException
description:
  condition: >-
    CommandInvoker receives response message with status indicating the service encountered an unexpected condition.
  expect: >-
    Invocation throws 'internal logic error' exception.

prologue:
  invokers:
  - { }

actions:
- action: invoke command
  invocation-index: 0
- action: await publish
  correlation-index: 0
- action: receive response
  correlation-index: 0
  status: "500" # Internal Server Error
  is-application-error: "false"
  metadata:
    "__propName": "Buffer"
- action: await invocation
  invocation-index: 0
  catch:
    error-kind: internal logic error
    is-shallow: !!bool false
    is-remote: !!bool true
    supplemental:
      property-name: 'buffer'
...
